server:
  port: 9090

spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6739
  datasource:
    url: jdbc:h2:tcp://localhost/~/chat
    username: sa
    password:
    driver-class-name: org.h2.Driver

  devtools:
    livereload:
      enable: true
    restart:
      enable: true
    freemarker:
      cache: false
